#!/usr/bin/env bash
#
# Subversion properties
#
# $LastChangedDate: 2006-06-22 10:51:47 -0700 (Thu, 22 Jun 2006) $
# $Author: misha $
# $Revision: 56 $
# $HeadURL: http://capps.moltenmagma.com/svn/sfsrc/trunk/sfapi2/sfui/launcher $
# $Id: launcher 56 2006-06-22 17:51:47Z misha $
#
# if 'bash' gives us bash v1, try to relaunch script bash v2 by name
BASHVER=`echo $BASH_VERSION | cut -b 1 -`
if [ $BASHVER = "1" ]; then
    exec bash2 $0 $*
fi

RAWPATH=$0
while [ -L $RAWPATH ]; do
    RAWPATH=`readlink $RAWPATH`;
done
LAUNCHERNAME=`basename $RAWPATH`
LAUNCHERDIR=`echo $RAWPATH | sed -e 's/\/[^\/]*$//'`
# get the absolute pathname of LAUNCHERDIR
CURDIR=`pwd`
if [ $LAUNCHERNAME != $LAUNCHERDIR ]; then
    cd $LAUNCHERDIR
fi
LAUNCHERDIR=`pwd -P`
cd $CURDIR

SFORCE_HOME=$LAUNCHERDIR/..
SFLIBDIR=$SFORCE_HOME/sflib
SFUTILDIR=$SFORCE_HOME/sfutil
. $SFLIBDIR/paths.sh

PYTHONPATH=$SFLIBDIR
export PYTHONPATH

scriptlist=( qor2sf loadqor crtbs resetbranch )


case $LAUNCHERNAME in

    qor2sf)       RUNCMD="walkQOR.py -cload1 $*";;
    loadqor)      RUNCMD="walkQOR.py -cload2 $*";;
    crtbs)        RUNCMD="walkSCM.py -wcrtbs $*";;
    resetbranch)  RUNCMD="walkSCM.py -wreset $*";;


    launcher)
        # get a copy of the scriptlist
        launcherlist=${scriptlist[*]}

        # add "mklinks" to the end of it
        #launcherlist[${#launcherlist[*]}]=mklinks

        CURDIR=`pwd`
        cd $LAUNCHERDIR

        for script in ${launcherlist[@]};
        do
            if [[ $1 == 'rm' ]]; then
                echo "removing $script"
                rm -f $script
            fi

            if [ ! -e $script ]; then
                ln $LAUNCHERNAME $script
            fi
        done

        cd $CURDIR
        ## commands to hard link launcher script to all the individual
        ## command names
        exit;;

    *)
        echo "ERROR: launcher unhandled case"
        exit;;
esac

# use it as the basis of the python script name
if [[ -z $SCRIPTPATH ]]; then
    SCRIPTPATH=$SFLIBDIR/$RUNCMD
fi

PYTHON_EXE=`which python2.3`

UNAME=`uname`
if [ $UNAME = 'Linux' ]; then
    $PYTHON_EXE $SCRIPTPATH
else
    echo 'Solaris not supported!'
fi

