#----------------------------------------------------------------------
# This file was generated by C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

runsoftware_16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABi9J"
    "REFUWIWll9uOJEcRhr+IyKyunundsXc5XHFpbJkH8LW5BCT8VBaPYF4A+12Ae0ACJBbJErDy"
    "7k4fqiozIriont7xCc/ilPqiurIyv4j845Aiajxk/PEPv8+fvvsuHoGKYGaoyIO+/V+jPHRi"
    "751lXujumCrDUEn7MrwAqnp5znvvMpOIYJ4mlmWhlEKp9Q0A2grQelutV+GrvlMR5PzLzC8B"
    "RAS9d/aHA4fbPeM4Ml5tHw7gEUTGunAm7g4iqChqerHSI5CvWH/3bgVJmjvWO9bawwEigzgv"
    "kpmEByKO2msdJJAR37HOCtnd6W8C8KVFzu5McnW3g4h86fy/aWSugO6O905X/f8AMpPWO5GJ"
    "miGqyAMjIjOJ3ukiqMjDAZor3QVJLpvd10I5P3+XJ1SFYoaqXb57GEA3uitFBeG1FtwdOIeg"
    "GfYdnjAzaq2r58weDvDiWPjPfsDEUAlUwRRqgVqVTSilCEVB1ddwvMTCXQQEEWt4phiq5eEA"
    "/95XNi9HyKQo1JIMNRhLMG7gKpRNCFWDYokpqCQQq/rOAO6OZyIIyBsAdBemZniACgyeDBF0"
    "D3omkUoP2BSoAaaCaqIIKnEGEJARrWB1g71JJiy2brwEdCBTSJQMISLxUJqDb5Sh3HmAszfO"
    "mkGgFio7alFKeYNa8JMfb7naObcnIRIGWy2MCJoL2dZ5pgLIBSBILEEkASFlQIuAQpLfDvDZ"
    "Z5/mkydPAHh88wOe/uht5nCe34I7XG1Wl786OHMT3KGp0vq6cRYwgXTB47VHznIgztL4VoAP"
    "PviAp0+fnievNeAwOwJEKOMQTEsyzU7rQqbiAa2DyDktG0iePWErUOS6uQgI35AHPv30d/nO"
    "O++w2+0u/2Uk4c4gwlvXigiYJqrJOCRzS4IkEpZ+rxAlcLYcVrd3h54rjCnIVxuSZ8/+kdfX"
    "1+v358rXmrMsDRXFaqHWQi3GaUn+9cJ5dYDZKy0KGWum3JQ1R4iusPUM3FzpseaLoveO4Lef"
    "fJLvvfcexYze++uYdec4NfaHBRFjMwzsdiM3uy3bwfjhDVwNye0E+yk4LsrSzw5IsLIeQw9H"
    "JWheaGGEgt8H+PmHH3J1dY2K0nunu6+lNZPeneNpBtbGxAyux8q4qVxvQIHFg9OyxvqqibPI"
    "ctWCyZqYmictIO7C9A6g1oqqEBn07rTeGOrAdtyQCNPxyNIa3jvLnJxOBmwQEVoTpjk5Tsa0"
    "CK3rKsLkIsxihonSU/BYtSD3AVSVJInIs+rXwjGOI+GN7QYkFyIWJDptKZgmokrvSrhAdkqc"
    "yIASiiKQSiBEKilr6HaHao5ZUH7z8cf5/s/eX8/93HKpGuMwMJSCiGCWbDfBoCeUl6huSQaW"
    "BRAhwrgeCjVPLO2fhL9EZAM60nNDZ0PmhoiBPgt9gce7I0+3R8qvP/oIVcHDiQxEhGKFYaiU"
    "C4AwDAKWFFnIMKZs9N7u/MdGk81wJOvnEJ8jtiV0ZI4NS4x4bmk50jv0Ba7ixGM9UW5ubliW"
    "mdYaxcqlXTYriN01FhVkRyfpsQUqqTtUK+mxxr8n4kbZPKGUAA0KHWsvGfu/SSqexqPqNBzj"
    "hsN8Q9kf9sg9HZgZVgw1Re9aLSmgW0KMHo8QUUwNIQlveATNHU3FhrdQUYQjGnsKeyRvzxk1"
    "yTITdG6zcJifvk5Ef/nzn9K0AMlmO3J1dUWtlWLGPM/s9wd6b+Rdx5PgvTNNJ3qPFcpgKJ2i"
    "DaEjuYCfwOe1kW2d4/HINJ1wewsvb99PxYK7sywzYspms8HUiLtLxrnfM7O1FeuOe2dZGuFB"
    "rQUwUra47FZCgRRIW7voxRdexC2vlj1DLQx6rx8Yx3HtWNNZ5oUv2heM48ju+hoPv0D03umt"
    "MU2rVbVWbDRUFdXzrYi1YnqsRxTeWJbOMk/s97fsX91yc/OY4erqngdkvVrVWjkeT0zTdBam"
    "rZac73buwbIsHI8HALbbq0sX7B7rnAhaT5Ye+DLR28SyNOZ54sWLL3j58hVDLTza7b5ejP7+"
    "t7+mirK0dgFqvXE6TYgIwzCQGczzzLNnz/jFL3/1va7IXyvHpsqjR48ulk7zxOk0sT8cGGpl"
    "GAZqHTArPH/+/PvsDcB/AcGJ5k3zdCVmAAAAAElFTkSuQmCC")
getrunsoftware_16x16Data = runsoftware_16x16.GetData
getrunsoftware_16x16Image = runsoftware_16x16.GetImage
getrunsoftware_16x16Bitmap = runsoftware_16x16.GetBitmap

