#----------------------------------------------------------------------
# This file was generated by C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

salesforce_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAyRJ"
    "REFUWIXt1l1InmUcx/HP86jTtDnNRVuzshYrHHshYWydaIMYg4mDxgZhzFlRC0JbNTpp+kT0"
    "dpC5gqAXVhEEFq6Q0bYDsyhdL5Rj5Mm0RISRsfbkWi6nz9PBvRtf5wsLHg/6ndwv13X9ua7v"
    "/bv//3/EPPXGk2ll0N2esRv6d2zKg+0X9jVC5YHytvnEi853A/+1IrNNCE98qCVRBy1DysaP"
    "p60uBNGVN4EzO2+JwdrSj+rnsoGFR6C6PFoFx7qSNfD9sPWwaFMZyNxYCv458SW41NkOcl9p"
    "AAV3rIvDy3dl3Qo1QyXxmTaQcgLpPZVp26H4m0QDPN+ZLIIXC4tA/jvNIKN4/cSVDTEw3NEW"
    "XL89AYYq9uZBT+bXtVAzpH6mDaScQOStkkgDbBtQO34g/+3DIGtLBUgMBp9y6OP3wcXjn2GM"
    "QCQ/Byxt+QFktLweh8anq2f0QuoJ3HkmswhaNwz/On5geV9iwsTw5H9/ElwziteB0f5ecPFY"
    "QCT7oQdB7lOvgv57MmJw83fX1E+3gdQTCG9q10YOwf5zqpjqgdkUEojvrwTXPvMsWLbl/ji8"
    "UDgwrRcWDoHJXgj/++uaWkE0N29OAQfuvg1k7boPLH74QPB+78YYLPugq378/IVDIFRFceQw"
    "vHne9pkWht4IvRLq7K7NYHTgF3D9kVMgu+/UtDUi5QTSJ7+4d2u0ETQlJhDIrQuqXcbqwBvp"
    "l/NAqDAfhJkx1LnYA2Bg1Zo86D3aE2Tc0qBGpJzAFTuiklWRLxjrgJYe/RFTq+Klrk7w575q"
    "MPjzyeB5eREYTo6AnLQhcOOKJXEoaO7OZwEQmOKBUHvKo0HBb0qUwYV3A2uE+WC4I+iI/ug5"
    "HTxv3gaSVU9MCBw9+zt49Kvm96B9T3cQt/ny+NWf4eo0a1e8YmXkJ8Z6w8FEsOT8mg0gc/dj"
    "QaDsoB9YHEnG4ZFFI5/C8WRNDJJbf+udLn7KCVzRA6EOlgT1fEnHaB2cHglIRPt6QU7rkTi0"
    "vfRcIzwe2/kajB48OWM3HCrlBGb1wJQFn99QBMkP/yqCtILbO5n7iScr5QT+17+9Yfi2NEqW"
    "QQAAAABJRU5ErkJggg==")
getsalesforce_iconData = salesforce_icon.GetData
getsalesforce_iconImage = salesforce_icon.GetImage
getsalesforce_iconBitmap = salesforce_icon.GetBitmap

