#----------------------------------------------------------------------
# This file was generated by C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

salesforce_icon2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACBxJ"
    "REFUWIXtlltwVdUdxn9r7X3u5yTnhBOSICEEBSMXQVQiBIutvWgZqamttaPFmdaO1V6GaTvT"
    "qZ3yUB3tW6fUsVjbKaLVjlpb0IKtDHiBiEAIRCOQQMIlCeeScE4OOde911p9CJJQO32rffGb"
    "2ZfZ+7/W+ub7X+ET/J8hXNcxliX+u5VyoVKBQAQXEID5NxN54ZqE85Evk5YCIcSVwFlbSIt8"
    "GTQf3dUYDUqjAz5UwEdoNIs/eRZjX+Q/sUiBDvuoBH1QGEf5IxQiMxBKX7KluXCPBQC4Fdhu"
    "FyuG3f2aitKUlQEEHjRaG8q+AMpvER08SfMrTzN7yyZM4hRIAy4TrL0gylCZGyfZvpxgwxWU"
    "UoPsWLKeXHw+ulzCIHE1KANKGx5s8wHMBXbbxoA2BlsKlKtQRlIO+VE2TOvrYc5f/8Csvz+D"
    "NzECCowAwkC8FnxeTCYNooL/1Cj+/rNEvv848fwY83fupiN+FZYUaMAjmFBKCIyZ1MXWRlBy"
    "DT6PxIoF0Bqmdb7D5S9tZOY/X8A+XwIPKA+IT98I7V+BFSsR9TPA68WsXgVd7yO9htCBo5SO"
    "7iWw8k4WtxY40vcBuekL8bhFXC0xBlxtQEzGnC2EQUoQbonaPXtoevZxGt5+FQpAFeiggHAU"
    "seFJxB1fvbhQAEYrhONMvHstgifHyb6+DXf57firqpif38eucgshKXA1ONrgKJgiADZao0Ne"
    "ajrepHXtLSDBhMHELISrEXYQXn4V0boC4yqQAqTEAEZaFwloDJYA75ZtVL7Vh3tkP41ndhIN"
    "Xkc6Oh/pFFH6gvxTCEgjBFbBIXd9G2PXXYP2WhhLIjAwZjAP3A+tKzDl0sThTgXzxK/R996J"
    "vv8bmNwYxicR2mACEDySpvLyJnwr1iDHU7Qcf5GCFpRdg0YgPpTvIgEkpaJDMRxk+J51yKKa"
    "+G8MxgesbkdoDUJO+O7baxHfXYfc/CL2755FnhqFooaKwVgWlgTx/Gb0WIL4D37P3OL71Ca6"
    "KVpBHEfhaHFJakptDA4WIuuQ+vwd5BfOg4JGGIMIWoiqaoyYkB1jMJUyhDyYpihmaQtm1XJo"
    "vQ4TCcM5hQkIwn0pxjauR8Sm03DfoyxNvUrFURgjUMpcUnAkQoAQSNfFiYUYumcdogRFj02h"
    "oCCduOA3g5AS8exLmANdsOcw7DkIOztg1154pxvxnfsw4wbpgPetfSQ2/RTic1i2ahmXpd6l"
    "YgfB6EtjQGCwhMH2WHjzLpkv3UWuZRZjFYWsgNr+ClJKtOtitEbYHkTLAuRls8DnxyiFsCx0"
    "UzPO408h7mhH5CE6kEF1H2BgwwME5y6hLZZElQtYtnVJGkrMRGBoI6DsUI7H6Fn9day8wYkJ"
    "7M1Pk+3az6jfO1GELkDBhHKWxeDgSc6cOIoXUA+tZ7TKIpsZJ3csRVmXSW/fzLIlc2jKHaaE"
    "D2H0FAIYFBYlR+EYGBs+x7HFN5JtiODVMDieo/PudvSObZAv4JSLqJE0bude1M6dHNjxCkdP"
    "9dI0ey4D/cc4JMpUFsxFueDp7kPE5nDW2KTGMlzvPYatigg52aSktCTFfJZU4hTG9nL6SBdH"
    "VYHybWsROcNbUQ+V4SF6vraGE22L8dxwDanWRRy9pY0tt99M193tLPFE2P72a3Ts3cWs2VdS"
    "N28RfQb6HUXn88+Rmr2YuqtvwuMmke89Q1k7k4XIKRdIDhxkxqwWUuk0u177I2u++RByyWd4"
    "feufqC9k6Qja1LmK08f7SQjoDEw027gPGh3Fk795mOovfJE7P/dlqr0BnkudZm81zLMEwd4T"
    "zOl+gw29Rwik09zsH2Nq95duuUC5kEG5moN7XsDgovKCFw6/ycvxIFuloMdogh4v02sbeKra"
    "JhcOUm6sZzxez8ZFl7No7X2ElaHj4G5+/L27+cuhd2n2QF4IolryyK8eJfLBG1y7dBXV6W6q"
    "88lJBSzbi7Q8vL3tSd7ft4XVd61j63O/ZHCwh6sXtpIa3cp4ThFuaOBTIkD/yDl+6/Pwwwd/"
    "wr79u6mMlejpfpfOri6yuRxXZUexpCBjJL1e6HFc6twqGnNDbPvzBpp1gWunKGALaSOFRerM"
    "AQqFLJ0dO/D64HxyiBP1jbTU1JNPDpH3BvAaH42ujVKG9Y89TG1NDdc0l1izrETUo3npsS5G"
    "fIr8zOkcSqZRJY0J2gSqQmzZd5rKFc1U3BKFcmXSBbZtMTTUzZFTvVQ1zCA9fIbe7i4yo1kK"
    "w+eYf287lQXT6T6fJTOe4bQuE6+pojocpG3lQj67PMiCxsu5beVN5LXioD9C3vJytqSpNM8k"
    "54uSq4uhtcP+vl6OFW1cM5kF9nghx/D+7azKluifJsnkRxnPZgkEQyROfkBKxZjV1sLf9g1z"
    "IH+eWLwZqvxUC6ht9FEbE1Adp5iqZtDYhMMREkWDG/bTEp/B2cooJ8YNkWiE+myeRLFEYUov"
    "sAuZEZb+4x1+FKvlF8khNpbOc1kgyPBwkpqGRtKJYfIll8jAALt9Fr4TSQL1IXyWZmw0xBt9"
    "55gWfovDw3XkcPHKEqN9aabXhkmUi/SOJBjpz1PXECdiBahkkig9WYjseM00bv35z/CFpnFb"
    "SFLndan1+Uknx6hrupJoeBQpJGrmAO95bCpKEQmH8AnF4htmc6gryc7jGSLRCI8+shx/wGL4"
    "ZJKg38fs5ib6+09SUZpQTRXC0QQiAaqroxcJCDN1QPsYIYTYAGyyhRDzgFuAK7hkVPifQgPH"
    "gfMfzrj1F54fFwwwDiQ+xjM/wX/GvwD6WdCgK+luhQAAAABJRU5ErkJggg==")
getsalesforce_icon2Data = salesforce_icon2.GetData
getsalesforce_icon2Image = salesforce_icon2.GetImage
getsalesforce_icon2Bitmap = salesforce_icon2.GetBitmap

